### ISSUE TITLE
Option to avoid logs flood

### ISSUE THREAD

**Issue by marcoturi** [ajbrown/angular-loggly-logger#59] opened 2016-07-15 08:17 UTC
Hi,
I' would like to have an option to avoid flood logs from one user. Thank you for this project :)

**Comment by ajbrown** [comment] 2016-08-03 17:43
@marcoturi Thanks for the feedback.  I'll be putting some thought into this over the weekend.

**Comment by ajbrown** [comment] 2016-08-03 17:44
duplicate of #58

**Closed by ajbrown** 2016-08-03 17:44 UTC
Labels: enhancement
